questions = [
    ('Are you wheezing?', 'wheezing'),                          
    ('Are you short of breath?', 'breathlessness'),             
    ('Do you have chest tightness?', 'chest_tightness'),       
    ('Do you have a high temperature?', 'high_temp'),          
    ('Do you have chest pain?', 'chest_pain'),                 
    ('Are you coughing?', 'cough'),                             
    ('Do you have joint pain?', 'joint_pain'),                 
    ('Do you have stiffness?', 'stiffness'),                   
    ('Do you have swelling?', 'swelling'),                     
    ('Do you have diarrhea?', 'diarrhea'),                      
    ('Are you vomiting?', 'vomiting'),                          
    ('Do you have nausea?', 'nausea'),                          
    ('Do you have numbness or weakness?', 'numbness_weakness'), 
    ('Are you confused?', 'confusion'),                         
    ('Do you have trouble speaking?', 'trouble_speaking'),     
]